### ISSUE TITLE
New version with dependency of 'rubyntlm', in '~> 0.3.2'

### ISSUE THREAD

**Issue by botularius** [omniauth/omniauth-ldap#53]
We are using your gem and having a problem with an older dependency of it.
We need the 'rubyntlm', in '~> 0.3.2'
I saw that you already updated the .gemspec file accoringly but you did not create a new version in rubygems.
Could you please do so??

**Comment by joenas** [comment]
:+1:

**Comment by rudyrigot** [comment]
+1

**Comment by ericschoville** [comment]
Also having this problem.

**Comment by botularius** [comment]
Please do so. I really have a bad feeling fetching from a github master branch...

**Comment by tmilewski** [comment]
Updated in `v2.0.0`
